config/routes.rb
Rails.application.routes.draw do
  root to: 'top#index'

  get 'login' => 'login#new', as: :new_login
  post 'login' => 'login#login'
  get 'login/destroy' => 'login#destroy', as: :destroy_login

  get 'users/home' => 'users#home', as: :home_user
  resources :users
  post 'users/:id/activate' => 'users#activate', as: :activate_user
  post 'users/:id/deactivate' => 'users#deactivate', as: :deactivate_user

  resources :seminors
  get 'seminors/:id/attend' => 'seminors#attend', as: :attend_seminor
  post 'seminors/:id/activate' => 'seminors#activate', as: :activate_seminor
  post 'seminors/:id/deactivate' => 'seminors#deactivate', as: :deactivate_seminor

  resources :event
  get 'event/:id/attend' => 'event#attend', as: :attend_event

  get 'attends/:seminor_id' => 'attends#new', as: :new_attend
  resources :attends
  post 'attends/:id/activate' => 'attends#activate', as: :activate_attend
  post 'attends/:id/deactivate' => 'attends#deactivate', as: :deactivate_attend

  get 'absent/:seminor_id' => 'absent#new', as: :new_absent
  resources :absent

  resources :reports

  get 'comments/:report_id' => 'comments#new', as: :new_comment
  resources :comments

  get 'minutes/:seminor_id' => 'minutes#new', as: :new_minutes

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string(255)      default(""), not null
#  name            :string(255)      default(""), not null
#  student_no      :string(255)      default(""), not null
#  password_digest :string(255)
#  state           :integer          default(0), not null
#  grade           :integer          default(0), not null
#  created_at      :datetime
#  updated_at      :datetime
#

class User < ActiveRecord::Base
  has_secure_password

  validates :email, presence: true, uniqueness: true
  validates :student_no, presence: true, uniqueness: true
  scope :id_is, -> (id) { where(id: id).first }

  has_many :attends
  has_many :reports
  has_many :comments

  include State
  include Grade

  def last_name
    name.split(' ').first
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :load_user
  before_action :authenticate_user!
  before_action :admin_user!, except: [:home, :index, :show, :edit, :update]

  def home
    seminors = Seminor.where(end_at: (Date.today)..(Date.today + 1.year))
    @undecide_seminors = []
    @undecide_events = []
    seminors.each do |seminor|
      if seminor.attends.user_is(current_user.id).first.nil?
        @undecide_events << seminor and next if seminor.event?
        @undecide_seminors << seminor
      end
    end
  end

  def index
    @users = User.all.order(grade: :desc)
  end

  def show
  end

  def new
    render :show_modal_form
  end

  def create
    @user = User.new(user_params)
    @result = @user.save
    @user = nil unless @result
    flash[:notice] = '登録しました。' if @result
  end

  def edit
    redirect_to home_user_path if !current_user.admin? && params[:id].to_i != current_user.id
    render :show_modal_form
  end

  def update
    redirect_to home_user_path if !current_user.admin? && params[:id].to_i != current_user.id
    @result = @user.update(user_params)
    @user = nil unless @result
    flash[:notice] = '更新しました。' if @result
  end

  def activate
    @user.state = State::ACTIVE
    @result = @user.save
    @user = nil unless @result
    flash[:notice] = '復帰しました。' if @result
    flash[:alert] = '復帰できませんでした。' unless @result
    render :reload
  end

  def deactivate
    @user.state = State::INACTIVE
    @result = @user.save
    @user = nil unless @result
    flash[:notice] = '無効化しました。' if @result
    flash[:alert] = '無効化できませんでした。' unless @result
    render :reload
  end

  def destroy
    @result = @user.attends.destroy_all
    @result = @user.destroy if @result
    @user = nil unless @result
    flash[:notice] = '削除しました。' if @result
    flash[:alert] = '削除できませんでした。' unless @result
    render :reload
  end

  private

  def load_user
    @user = User.id_is(params[:id]) if params[:id]
  end

  def user_params
    params.require(:user).permit(:email, :name, :student_no, :password, :password_confirmation, :state, :grade)
  end
end

app/views/users/_form.html.slim
- unless @user
  - @user = User.new
  - @title = '新規登録'
  - @button_caption = '登録'
- else
  - @title = '編集'
  - @button_caption = '更新'

= form_for @user, html: { class: 'form-horizontal' }, remote: true do |f|
  - modal_body = capture do
    .form-group
      = f.label :name, '名前', class: 'col-md-4 control-label'
      .col-md-5
        = f.text_field :name, autofocus: true, class: 'form-control', placeholder: '例) 研究 太郎'
    .form-group
      = f.label :student_no, '学籍番号', class: 'col-md-4 control-label'
      .col-md-5
        = f.text_field :student_no, autofocus: true, class: 'form-control', placeholder: '例) 00T000'
    .form-group
      = f.label :email, 'メールアドレス', class: 'col-md-4 control-label'
      .col-md-5
        = f.text_field :email, autofocus: true, class: 'form-control', placeholder: '例) 00t000@labolife-u.ac.jp'
    .form-group
      = f.label :password, 'パスワード', class: 'col-md-4 control-label'
      .col-md-5
        = f.password_field :password, autocomplete: 'off', class: 'form-control'
    .form-group
      = f.label :password_confirmation, 'パスワード (確認)', class: 'col-md-4 control-label'
      .col-md-5
        = f.password_field :password_confirmation, autocomplete: 'off', class: 'form-control'
    - if current_user.admin?
      .form-group
        = f.label :grade, '学年', class: 'col-md-4 control-label'
        .col-md-5
          = f.select :grade, Grade::SELECT, {}, { class: 'form-control' }

  - modal_footer = capture do
    = f.submit @button_caption, class: 'btn btn-primary'
    = content_tag :button, "キャンセル", class: 'btn btn-default', 'data-dismiss' => 'modal'

  - modal_dialog :id => "modal-form", :header => { :show_close => true, :dismiss => 'modal', :title => @title }, body: modal_body, :footer => modal_footer

app/views/users/_list.html.slim
.table-responsive
  table.table.table-condensed.table-bordered
    thead
      - if current_user.admin?
        th
      th 学年
      th 名前
      th 学籍番号
      th メールアドレス
    tbody
      - @users.each do |user|
        - unless user.active?
          - next unless current_user.admin?
          - accent = 'active'
        tr class="#{accent}"
          - if current_user.admin?
            td
              - if user.active?
                = link_to edit_user_path(user.id), class: "btn btn-success btn-xs", remote: true do
                  span.glyphicon.glyphicon-pencil
                  | &nbsp;編集
                | &nbsp;
                = link_to deactivate_user_path(user.id), class: "btn btn-danger btn-xs", remote: true, method: :post do
                  span.glyphicon.glyphicon-ban-circle
                  | &nbsp;無効
              - else
                = link_to activate_user_path(user.id), class: "btn btn-primary btn-xs", remote: true, method: :post do
                  span.glyphicon.glyphicon-repeat
                  | &nbsp;復帰
                | &nbsp;
                = link_to user_path(user.id), class: "btn btn-danger btn-xs", remote: true, method: :delete do
                  span.glyphicon.glyphicon-remove
                  | &nbsp;削除
          td
            = Grade::TEXT[user.grade]
          td
            = link_to user_path(user.id) do
              span.glyphicon.glyphicon-hand-right
              | &nbsp;
              = user.name
          td
            = user.student_no
          td
            = user.email

app/views/users/home.html.slim
- @title = 'ホーム'

h3.bold #{@title}

- unless @undecide_seminors.empty?
  .bs-callout.bs-callout-danger
    h4 出欠が未定のゼミナールがあります!
    p
    - @undecide_seminors.each do |seminor|
      = link_to attend_seminor_path(seminor.id), class: 'btn btn-sm btn-default', remote: true do
        span.glyphicon.glyphicon-flag
        | &nbsp;#{seminor.start_at.strftime('%Y/%m/%d %H:%M')} 『#{seminor.caption}』
      p

- unless @undecide_events.empty?
  .bs-callout.bs-callout-warning
    h4 出欠が未定のイベントがあります!
    p
    - @undecide_events.each do |event|
      = link_to attend_event_path(event.id), class: 'btn btn-sm btn-default', remote: true do
        span.glyphicon.glyphicon-flag
        | &nbsp;#{event.start_at.strftime('%Y/%m/%d %H:%M')} 『#{event.caption}』
      p

- if @undecide_seminors.empty? && @undecide_events.empty?
  .bs-callout.bs-callout-info
    h4 お知らせはありません。

app/views/users/index.html.slim
- if current_user.admin?
  - @title = 'ユーザー管理'
- else
  - @title = 'ユーザー'

h3.bold #{@title}

- if current_user.admin?
  = link_to new_user_path, class: 'btn btn-info', remote: true do
    span.glyphicon.glyphicon-plus
    | &nbsp;新規登録

p

= render partial: 'users/list'

app/views/users/show.html.slim
- @title = @user.name

h3.bold #{@title}

p

.table-responsive
  table.table.table-condensed.table-bordered
    tbody
      tr
        td.active
          strong 名前
        td #{@user.name}
      tr
        td.active
          strong 学籍番号
        td #{@user.student_no}
      tr
        td.active
          strong メールアドレス
        td #{@user.email}
      tr
        td.active
          strong 学年
        td
          = Grade::TEXT[user.grade]

h3.bold 報告・発表

- reports = @user.reports.order(updated_at: :desc)
- if reports.first.nil?
  strong なし
- else
  .table-responsive
    table.table.table-condensed.table-bordered
      thead
        th
        th キャプション
        th 更新日時
      tbody
        - i = 1
        - reports.each do |report|
          tr
            td #{i}
            td
              | &nbsp;
              = link_to report_path(report.id)  do
                span.glyphicon.glyphicon-hand-right
                | &nbsp;
                = report.caption
            td #{report.updated_at.strftime('%Y/%m/%d %H:%M')}
          - i += 1