config/routes.rb
Rails.application.routes.draw do
  root to: 'top#index'

  get 'login' => 'login#new', as: :new_login
  post 'login' => 'login#login'
  get 'login/destroy' => 'login#destroy', as: :destroy_login

  get 'users/home' => 'users#home', as: :home_user
  resources :users
  post 'users/:id/activate' => 'users#activate', as: :activate_user
  post 'users/:id/deactivate' => 'users#deactivate', as: :deactivate_user

  resources :seminors
  get 'seminors/:id/attend' => 'seminors#attend', as: :attend_seminor
  post 'seminors/:id/activate' => 'seminors#activate', as: :activate_seminor
  post 'seminors/:id/deactivate' => 'seminors#deactivate', as: :deactivate_seminor

  resources :event
  get 'event/:id/attend' => 'event#attend', as: :attend_event

  get 'attends/:seminor_id' => 'attends#new', as: :new_attend
  resources :attends
  post 'attends/:id/activate' => 'attends#activate', as: :activate_attend
  post 'attends/:id/deactivate' => 'attends#deactivate', as: :deactivate_attend

  get 'absent/:seminor_id' => 'absent#new', as: :new_absent
  resources :absent

  resources :reports

  get 'comments/:report_id' => 'comments#new', as: :new_comment
  resources :comments

  get 'minutes/:seminor_id' => 'minutes#new', as: :new_minutes

end

app/models/seminor.rb
# == Schema Information
#
# Table name: seminors
#
#  id               :integer          not null, primary key
#  chairman_user_id :integer          not null
#  created_user_id  :integer          not null
#  caption          :string(255)      default(""), not null
#  state            :integer          default(0), not null
#  created_at       :datetime
#  updated_at       :datetime
#  start_at         :datetime         not null
#  end_at           :datetime         not null
#  place            :string(255)      default(""), not null
#

class Seminor < ActiveRecord::Base
  validates :chairman_user_id, presence: true
  validates :created_user_id, presence: true
  validates :start_at, presence: true
  validates :end_at, presence: true
  validates :place, presence: true
  validates :caption, presence: true
  scope :id_is, -> (id) { where(id: id).first }

  has_many :attends
  has_many :reports

  include State

  def users(grade)
    attends.where(state: State::ACTIVE).map { |attend| attend.user if attend.user.grade == grade }.delete_if { |user| user.nil? }
  end

  def event?
    return true if chairman_user_id == 0
    return false
  end
end

app/controllers/seminors_controller.rb
class SeminorsController < ApplicationController
  before_action :load_seminor
  before_action :authenticate_user!
  before_action :admin_user!, except: [:index, :show, :attend]

  def index
    @seminors = Seminor.all
  end

  def show
  end

  def attend
    render :show_modal_attend
  end

  def new
    render :show_modal_form
  end

  def create
    @seminor = Seminor.new(seminor_params)
    @result = @seminor.save
    @seminor = nil unless @result
    flash[:notice] = '登録しました。' if @result
  end

  def edit
    render :show_modal_form
  end

  def update
    @result = @seminor.update(seminor_params)
    @seminor = nil unless @result
    flash[:notice] = '更新しました。' if @result
  end

  def activate
    @seminor.state = State::ACTIVE
    @result = @seminor.save
    @seminor = nil unless @result
    flash[:notice] = '復帰しました。' if @result
    flash[:alert] = '復帰できませんでした。' unless @result
    render :reload
  end

  def deactivate
    @seminor.state = State::INACTIVE
    @result = @seminor.save
    @seminor = nil unless @result
    flash[:notice] = '無効化しました。' if @result
    flash[:alert] = '無効化できませんでした。' unless @result
    render :reload
  end

  def destroy
    @result = @seminor.attends.destroy_all
    @result = @seminor.destroy if @result
    @seminor = nil unless @result
    flash[:notice] = '削除しました。' if @result
    flash[:alert] = '削除できませんでした。' unless @result
    render :reload
  end

  private

  def load_seminor
    @seminor = Seminor.id_is(params[:id]) if params[:id]
  end

  def seminor_params
    params.require(:seminor).permit(:caption, :start_at, :end_at, :place, :chairman_user_id, :created_user_id)
  end
end

app/views/seminors/_attend.html.slim
- @title = @seminor.caption

- modal_body = capture do
  .table-responsive style="border: none;"
    table.table.table-borderless
      tbody
        tr
          td
            strong 日時:&nbsp
          td
            | #{@seminor.start_at.strftime('%Y/%m/%d %H:%M')} ～ #{@seminor.end_at.strftime('%Y/%m/%d %H:%M')}
        tr
          td
            strong 場所:&nbsp
          td
            | #{@seminor.place}
        - if @seminor.active? && @seminor.end_at >= Time.now
          tr
            td.middle
              strong 出欠:&nbsp
            td
              - if @seminor.active?
                - attend = @seminor.attends.where(user_id: current_user.id).first
                - if attend
                  - if attend.active?
                    = link_to edit_absent_path(attend.id), class: "btn btn-warning btn-xs", remote: true do
                      span.glyphicon.glyphicon-minus
                      | &nbsp;欠席
                    | &nbsp;
                    = link_to edit_attend_path(attend.id), class: "btn btn-success btn-xs", remote: true do
                      span.glyphicon.glyphicon-pencil
                      | &nbsp;編集
                  - else
                    = link_to activate_attend_path(attend.id), class: "btn btn-primary btn-xs", remote: true, method: :post do
                      span.glyphicon.glyphicon-flag
                      | &nbsp;出席
                    | &nbsp;
                    = link_to edit_attend_path(attend.id), class: "btn btn-success btn-xs", remote: true do
                      span.glyphicon.glyphicon-pencil
                      | &nbsp;編集
                - else
                  = link_to new_attend_path(@seminor.id), class: "btn btn-primary btn-xs", remote: true do
                    span.glyphicon.glyphicon-flag
                    | &nbsp;出席
                  | &nbsp;
                  = link_to new_absent_path(@seminor.id), class: "btn btn-warning btn-xs", remote: true do
                    span.glyphicon.glyphicon-minus
                    | &nbsp;欠席

- modal_footer = capture do
  - if current_user.admin?
    - if @seminor.active?
      = link_to edit_seminor_path(@seminor.id), class: "btn btn-success", remote: true do
        span.glyphicon.glyphicon-pencil
        | &nbsp;編集
      = link_to deactivate_seminor_path(@seminor.id), class: "btn btn-danger", remote: true, method: :post do
        span.glyphicon.glyphicon-ban-circle
        | &nbsp;無効
    - else
      = link_to activate_seminor_path(@seminor.id), class: "btn btn-primary", remote: true, method: :post do
        span.glyphicon.glyphicon-repeat
        | &nbsp;復帰
      = link_to seminor_path(@seminor.id), class: "btn btn-danger", remote: true, method: :delete do
        span.glyphicon.glyphicon-remove
        | &nbsp;削除
  = link_to seminor_path(@seminor.id), class: "btn btn-info" do
    span.glyphicon.glyphicon-new-window
    | &nbsp;詳細
  = content_tag :button, "キャンセル", class: 'btn btn-default', 'data-dismiss' => 'modal'

= modal_dialog :id => "modal-attend", :header => { :show_close => true, :dismiss => 'modal', :title => @title }, body: modal_body, :footer => modal_footer

app/views/seminors/_form.html.slim
- unless @seminor
  - @seminor = Seminor.new
  - @title = '新規登録'
  - @button_caption = '登録'
- else
  - @title = '編集'
  - @button_caption = '更新'

= form_for @seminor, html: { class: 'form-horizontal' }, remote: true do |f|
  - modal_body = capture do
    = f.hidden_field :created_user_id, value: current_user.id
    .form-group
      = f.label :caption, 'キャプション', class: 'col-md-4 control-label'
      .col-md-5
        = f.text_field :caption, autofocus: true, class: 'form-control', placeholder: '例) 定例ゼミナール'
    .form-group
      = f.label :start_at, '開始日時', class: 'col-md-4 control-label'
      .col-md-5
        .input-group.date#datetimepicker_start_at
          = f.text_field :start_at, autofocus: true, class: 'form-control', placeholder: 'YYYY/MM/DD HH:mmy'
          span.input-group-addon
            span.glyphicon.glyphicon-calendar
    .form-group
      = f.label :end_at, '終了日時', class: 'col-md-4 control-label'
      .col-md-5
        .input-group.date#datetimepicker_end_at
          = f.text_field :end_at, autofocus: true, class: 'form-control', placeholder: 'YYYY/MM/DD HH:mmy'
          span.input-group-addon
            span.glyphicon.glyphicon-calendar
    .form-group
      = f.label :place, '場所', class: 'col-md-4 control-label'
      .col-md-5
        = f.text_field :place, autofocus: true, class: 'form-control', placeholder: '例) 研究室'
    .form-group
      = f.label :chairman_user_id, '議事', class: 'col-md-4 control-label'
      .col-md-5
        = f.collection_select :chairman_user_id, User.where(state: State::ACTIVE), :id, :name, {}, { class: 'form-control' }

  - modal_footer = capture do
    = f.submit @button_caption, class: 'btn btn-primary'
    = content_tag :button, "キャンセル", class: 'btn btn-default', 'data-dismiss' => 'modal'

  - modal_dialog :id => "modal-form", :header => { :show_close => true, :dismiss => 'modal', :title => @title }, body: modal_body, :footer => modal_footer

script type="text/javascript"
  | $(function () {
  |   $('#datetimepicker_start_at').datetimepicker({ format: 'YYYY/MM/DD HH:mm' });
  |   $('#datetimepicker_end_at').datetimepicker({ format: 'YYYY/MM/DD HH:mm' });
  | });

app/views/seminors/index.html.slim
- @title = 'カレンダー'

h3.bold #{@title}

- if current_user.admin?
  = link_to new_seminor_path, class: 'btn btn-info', remote: true do
    span.glyphicon.glyphicon-plus
    | &nbsp;ゼミナール登録
  | &nbsp;
= link_to new_event_path, class: 'btn btn-success', remote: true do
  span.glyphicon.glyphicon-plus
  | &nbsp;イベント登録

p

- @seminors = @seminors.where(state: State::ACTIVE) unless current_user.admin?
- seminors = @seminors.map do |seminor|
  - attend = seminor.attends.where(user_id: current_user.id).first
  - if attend
    - if attend.active?
      - color = '#428bca'
    - else
      - color = '#f0ad4e'
  - else
    - color = '#d9534f'
  - if seminor.event?
    - url = attend_event_path(seminor.id)
  - else
    - url = attend_seminor_path(seminor.id)
  - { title: seminor.caption, start: seminor.start_at.strftime('%Y-%m-%d %H:%M:%S'), end: seminor.end_at.strftime('%Y-%m-%d %H:%M:%S'), url: url.gsub('.', '/'), allDay: false, color: color }

#calendar
  script type="text/javascript"
    | $(document).ready(function() {
    |   $('#calendar').fullCalendar({
    |     header: {
    |       left: 'prev,next today',
    |       center: 'title',
    |       right: 'month,agendaWeek,agendaDay'
    |     },
    |     weekMode: 'liquid',
    |     contentHeight: 500,
    |     defaultView: 'month',
    |     allDaySlot: false,
    |     allDayText: '終日',
    |     axisFormat: 'H:mm',
    |     firstHour: 8,
    |     timeFormat: { '': 'H:mm', agenda: 'H:mm{ - H:mm}' },
    |     columnFormat: { month: 'ddd', week: "d'('ddd')'", day: "d'('ddd')'" },
    |     titleFormat: { month: 'yyyy年M月', week: "yyyy年M月d日{ ～ }{[yyyy年]}{[M月]d日}", day: "yyyy年M月d日'('ddd')'" },
    |     buttonText: { prev:'&lsaquo;', next: '&rsaquo;', prevYear: '&laquo;', nextYear: '&raquo;', today: '今日', month: '月', week: '週', day: '日' },
    |     monthNames: ['1月', '2月', '3月', '4月', '5月', '6月', '7月', '8月', '9月', '10月', '11月', '12月'],
    |     monthNamesShort: ['1月', '2月', '3月', '4月', '5月', '6月', '7月', '8月', '9月', '10月', '11月', '12月'],
    |     dayNames: ['日曜日', '月曜日', '火曜日', '水曜日', '木曜日', '金曜日', '土曜日'],
    |     dayNamesShort: ['日', '月', '火', '水', '木', '金', '土'],
    |     editable: false,
    |     events: #{raw seminors.to_json}
    |   })
    | });

p

div align="right"
  label.label.label-primary 出席
  | &nbsp;
  label.label.label-warning 欠席
  | &nbsp;
  label.label.label-danger 未定

script type="text/javascript"
  | $(function(){
  |   $('.fc-event').attr({ 'data-remote': 'true' });
  | });
  | $(document).on('click', '.fc-button', function(){
  |   $('.fc-event').attr({ 'data-remote': 'true' });
  | });

app/views/seminors/show.html.slim
- @title = @seminor.caption

h3.bold #{@title}

p

.table-responsive
  table.table.table-condensed.table-bordered
    tbody
      tr
        td.active
          strong 日時
        td #{@seminor.start_at.strftime('%Y/%m/%d %H:%M')} ～ #{@seminor.end_at.strftime('%Y/%m/%d %H:%M')}
      tr
        td.active
          strong 場所
        td #{@seminor.place}
      tr
        td.active
          strong 議事
        td #{User.id_is(@seminor.chairman_user_id).name}
      tr
        td.active
          strong 作成者
        td #{User.id_is(@seminor.created_user_id).name}
      tr
        td.active
          strong 出席者
        td
          - i = 0
          - @seminor.attends.where(state: State::ACTIVE).each do |attend|
            - if attend.report.nil?
              button.btn.btn-default.btn-xs data-toggle="tooltip" title="報告なし"
                = attend.user.name
            - else
              = link_to report_path(attend.report.id), class: 'btn btn-info btn-xs', title: attend.report.caption, 'data-toggle' => 'tooltip' do
                | &nbsp;#{attend.user.name}
            | &nbsp;
            - i += 1
            - if i % 5 == 0
              br
      tr
        td.active
          strong 欠席者
        td
          - i = 0
          - User.where(state: State::ACTIVE).each do |user|
            - attend = @seminor.attends.where(user_id: user.id).first
            - if attend.nil?
              button.btn.btn-danger.btn-xs data-toggle="tooltip" title="出欠未定"
                = user.name
            - elsif !attend.active?
              button.btn.btn-warning.btn-xs data-toggle="tooltip" title="#{attend.absent_reason}"
                = user.name
            | &nbsp;
            - i += 1
            - if i % 5 == 0
              br

h3.bold 報告・発表

- reports = @seminor.reports.order(created_at: :asc)
- if reports.first.nil?
  strong なし
- else
  .table-responsive
    table.table.table-condensed.table-bordered
      thead
        th
        th 報告・発表者
        th キャプション
      tbody
        - i = 1
        - reports.each do |report|
          tr
            td #{i}
            td #{report.user.name}
            td
              | &nbsp;
              = link_to report_path(report.id)  do
                span.glyphicon.glyphicon-hand-right
                | &nbsp;
                = report.caption
          - i += 1

= link_to new_minutes_path(@seminor.id), class: 'btn btn-info' do
  span.glyphicon.glyphicon-envelope
  | &nbsp;議事録

script type="text/javascript"
  | $('[data-toggle=tooltip]').tooltip()