config/routes.rb
Rails.application.routes.draw do
  root to: 'top#index'

  get 'login' => 'login#new', as: :new_login
  post 'login' => 'login#login'
  get 'login/destroy' => 'login#destroy', as: :destroy_login

  get 'users/home' => 'users#home', as: :home_user
  resources :users
  post 'users/:id/activate' => 'users#activate', as: :activate_user
  post 'users/:id/deactivate' => 'users#deactivate', as: :deactivate_user

  resources :seminors
  get 'seminors/:id/attend' => 'seminors#attend', as: :attend_seminor
  post 'seminors/:id/activate' => 'seminors#activate', as: :activate_seminor
  post 'seminors/:id/deactivate' => 'seminors#deactivate', as: :deactivate_seminor

  resources :event
  get 'event/:id/attend' => 'event#attend', as: :attend_event

  get 'attends/:seminor_id' => 'attends#new', as: :new_attend
  resources :attends
  post 'attends/:id/activate' => 'attends#activate', as: :activate_attend
  post 'attends/:id/deactivate' => 'attends#deactivate', as: :deactivate_attend

  get 'absent/:seminor_id' => 'absent#new', as: :new_absent
  resources :absent

  resources :reports

  get 'comments/:report_id' => 'comments#new', as: :new_comment
  resources :comments

  get 'minutes/:seminor_id' => 'minutes#new', as: :new_minutes

end

app/models/report.rb
# == Schema Information
#
# Table name: reports
#
#  id         :integer          not null, primary key
#  attend_id  :integer          default(0), not null
#  caption    :string(255)      default(""), not null
#  abstract   :text             default(""), not null
#  document   :string(255)
#  created_at :datetime
#  updated_at :datetime
#  user_id    :integer          default(0), not null
#  seminor_id :integer          default(0), not null
#

class Report < ActiveRecord::Base
  mount_uploader :document, DocumentUploader
  validates :user_id, presence: true
  validates :seminor_id, presence: true
  validates :caption, presence: true
  validates :abstract, presence: true
  scope :id_is, -> (id) { where(id: id).first }

  belongs_to :user
  belongs_to :seminor
  belongs_to :attend
  has_many :comments

  def document_exist?
    return false if document.path.nil?
    File.exist? document.path
  end

  def document_filename
    document.path.split('/').last
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :load_report
  before_action :authenticate_user!

  def show
  end

  private

  def load_report
    @report = Report.id_is(params[:id]) if params[:id]
  end
end

app/views/reports/_form.html.slim
= f.fields_for :report do |f_report|
  .form-group
    .checkbox
      label
        = f_report.check_box :_destroy, { checked: true }, false, true
        | 報告・発表する
  #attend_report_field
    .form-group
      = f_report.label :caption, 'キャプション', class: 'control-label'
      = f_report.text_field :caption, autofocus: true, class: 'form-control', placeholder: '例) 週間報告'
    .form-group
      = f_report.label :abstract, '要約', class: 'control-label'
      = f_report.text_area :abstract, autofocus: true, class: 'form-control', placeholder: '例) 作業内容など。', size: 'x5'
    .form-group
      = f_report.label :document, '資料', class: 'control-label'
      = f_report.file_field :document, style: 'display: none;'
      .input-group
        input.form-control type="text" id="selected_file" readonly="readonly"
        span.input-group-btn
          a.btn.btn-default onclick="$('#attend_report_attributes_document').click();"
            | ファイル選択

script type="text/javascript"
  | var report_field = $('#attend_report_field').html();
  |
  | $('#attend_report_attributes__destroy').change(function(){
  |   if ($(this).is(':checked')) {
  |     $('#attend_report_field').html(report_field);
  |   } else {
  |     $('#attend_report_field').empty();
  |   }
  | });
  |
  | $('#attend_report_attributes_document').change(function() {
  |   $('#selected_file').val($(this).val());
  | });

app/views/reports/show.html.slim
- @title = @report.caption

h3.bold #{@title}
p.monospace
  strong
    | 更新日時:&nbsp;
  | #{@report.updated_at.strftime('%Y/%m/%d %H:%M')}
  br
  strong
    | 作成者　:&nbsp;
  | #{@report.user.name}

.well
  p.monospace
    = linebreak_to_br @report.abstract

- if @report.document_exist?
  = link_to @report.document.url, class: 'btn btn-default', target: [:_blank] do
    span.glyphicon.glyphicon-file
    | &nbsp;#{@report.document_filename}

h3.bold コメント

= render partial: 'comments/list'

= link_to new_comment_path(@report.id), class: 'btn btn-info', remote: true do
  span.glyphicon.glyphicon-comment
  | &nbsp;コメントする