config/routes.rb
Rails.application.routes.draw do
  root to: 'top#index'

  get 'login' => 'login#new', as: :new_login
  post 'login' => 'login#login'
  get 'login/destroy' => 'login#destroy', as: :destroy_login

  get 'users/home' => 'users#home', as: :home_user
  resources :users
  post 'users/:id/activate' => 'users#activate', as: :activate_user
  post 'users/:id/deactivate' => 'users#deactivate', as: :deactivate_user

  resources :seminors
  get 'seminors/:id/attend' => 'seminors#attend', as: :attend_seminor
  post 'seminors/:id/activate' => 'seminors#activate', as: :activate_seminor
  post 'seminors/:id/deactivate' => 'seminors#deactivate', as: :deactivate_seminor

  resources :event
  get 'event/:id/attend' => 'event#attend', as: :attend_event

  get 'attends/:seminor_id' => 'attends#new', as: :new_attend
  resources :attends
  post 'attends/:id/activate' => 'attends#activate', as: :activate_attend
  post 'attends/:id/deactivate' => 'attends#deactivate', as: :deactivate_attend

  get 'absent/:seminor_id' => 'absent#new', as: :new_absent
  resources :absent

  resources :reports

  get 'comments/:report_id' => 'comments#new', as: :new_comment
  resources :comments

  get 'minutes/:seminor_id' => 'minutes#new', as: :new_minutes

end

app/views/layouts/application.html.slim
doctype html
html
  head
    title #{@title} | LaboLife
    meta name="viewport" content="width=device-width, initial-scale=1"
    = stylesheet_link_tag    'application', 'data-turbolinks-track' => true, media: 'all'
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  body
    .modal-attend
    .modal-form

    nav.navbar.navbar-inverse.navbar-fixed-top role="navigation"
      .container
        .navbar-header
          button.navbar-toggle type="button" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"
            span.sr-only Toggle navigation
            span.icon-bar
            span.icon-bar
            span.icon-bar
          = link_to root_path, class: 'navbar-brand' do
            = image_tag 'logo.png', class: 'brand-icon'
            span.brand-with-icon

        .collapse.navbar-collapse id="bs-example-navbar-collapse-1"
          - if current_user
            ul.nav.navbar-nav
              li
                = link_to home_user_path do
                  span.glyphicon.glyphicon-home
                  | &nbsp;ホーム
              li
                = link_to users_path do
                  span.glyphicon.glyphicon-user
                  | &nbsp;ユーザー
              li
                = link_to seminors_path do
                  span.glyphicon.glyphicon-calendar
                  | &nbsp;カレンダー
            ul.nav.navbar-nav.navbar-right
              li.dropdown
                a.dropdown-toggle href="#" data-toggle="dropdown"
                  span.glyphicon.glyphicon-user
                  | &nbsp;#{current_user.name}&nbsp;
                  b.caret
                ul.dropdown-menu
                  li
                    = link_to edit_user_path(current_user.id), remote: true do
                      span.glyphicon.glyphicon-pencil
                      | &nbsp;編集
                    = link_to destroy_login_path do
                      span.glyphicon.glyphicon-log-out
                      | &nbsp;ログアウト

    .container
      - if notice
        .alert.alert-info.alert-dismissable
          button.close type="button" data-dismiss="alert" aria-hidden="true" &times;
          = notice
      - if alert
        .alert.alert-danger.alert-dismissable
          button.close type="button" data-dismiss="alert" aria-hidden="true" &times;
          = alert
      = yield
      footer
        br
        p &copy; Enjoy Laboratory Project